# Generated by Django 3.2.4 on 2021-06-14 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0009_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='featured',
            field=models.BooleanField(null=True),
        ),
    ]
